
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/8/21 17:57:25。
      节点 1 上的项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.42
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/3.27.2/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/8/21 17:57:27。
      节点 1 上的项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\3.27.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.96
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/3.27.2/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-ni4ksw"
      binary: "E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-ni4ksw"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-ni4ksw'
        
        Run Build Command(s): E:/01_Adunas/Microsoft/VisualStudio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_64a42.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/8/21 17:57:28。
        节点 1 上的项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-ni4ksw\\cmTC_64a42.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_64a42.dir\\Debug\\”。
          正在创建目录“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-ni4ksw\\Debug\\”。
          正在创建目录“cmTC_64a42.dir\\Debug\\cmTC_64a42.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_64a42.dir\\Debug\\cmTC_64a42.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_64a42.dir\\Debug\\\\" /Fd"cmTC_64a42.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "E:\\01_Adunas\\02_EnglishPath\\03_software\\07_program\\02_C\\03_CMake\\02_FilePozition\\02_R7000\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27050 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_64a42.dir\\Debug\\\\" /Fd"cmTC_64a42.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "E:\\01_Adunas\\02_EnglishPath\\03_software\\07_program\\02_C\\03_CMake\\02_FilePozition\\02_R7000\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
          
        Link:
          E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-ni4ksw\\Debug\\cmTC_64a42.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-ni4ksw/Debug/cmTC_64a42.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-ni4ksw/Debug/cmTC_64a42.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_64a42.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_64a42.vcxproj -> E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-ni4ksw\\Debug\\cmTC_64a42.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_64a42.dir\\Debug\\cmTC_64a42.tlog\\unsuccessfulbuild”。
          正在对“cmTC_64a42.dir\\Debug\\cmTC_64a42.tlog\\cmTC_64a42.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-ni4ksw\\cmTC_64a42.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.20
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "E:/01_Adunas/02_EnglishPath/03_software/07_program/02_C/03_CMake/02_FilePozition/02_R7000/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-0dwcjt"
      binary: "E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-0dwcjt"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-0dwcjt'
        
        Run Build Command(s): E:/01_Adunas/Microsoft/VisualStudio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_e9e03.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/8/21 17:57:30。
        节点 1 上的项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-0dwcjt\\cmTC_e9e03.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_e9e03.dir\\Debug\\”。
          正在创建目录“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-0dwcjt\\Debug\\”。
          正在创建目录“cmTC_e9e03.dir\\Debug\\cmTC_e9e03.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_e9e03.dir\\Debug\\cmTC_e9e03.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e9e03.dir\\Debug\\\\" /Fd"cmTC_e9e03.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "E:\\01_Adunas\\02_EnglishPath\\03_software\\07_program\\02_C\\03_CMake\\02_FilePozition\\02_R7000\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27050 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e9e03.dir\\Debug\\\\" /Fd"cmTC_e9e03.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "E:\\01_Adunas\\02_EnglishPath\\03_software\\07_program\\02_C\\03_CMake\\02_FilePozition\\02_R7000\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          E:\\01_Adunas\\Microsoft\\VisualStudio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-0dwcjt\\Debug\\cmTC_e9e03.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-0dwcjt/Debug/cmTC_e9e03.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/01_Adunas/02_EnglishPath/07_program/18_ProgramLearn/ProgramLearn/example/SingleSrc/cmake/VS2017/CMakeFiles/CMakeScratch/TryCompile-0dwcjt/Debug/cmTC_e9e03.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_e9e03.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_e9e03.vcxproj -> E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-0dwcjt\\Debug\\cmTC_e9e03.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_e9e03.dir\\Debug\\cmTC_e9e03.tlog\\unsuccessfulbuild”。
          正在对“cmTC_e9e03.dir\\Debug\\cmTC_e9e03.tlog\\cmTC_e9e03.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\01_Adunas\\02_EnglishPath\\07_program\\18_ProgramLearn\\ProgramLearn\\example\\SingleSrc\\cmake\\VS2017\\CMakeFiles\\CMakeScratch\\TryCompile-0dwcjt\\cmTC_e9e03.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.91
        
      exitCode: 0
...
